import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import cli_reference  # noqa: E402

FIXTURE = '''
import argparse, os

def main(argv=None):
    parser = argparse.ArgumentParser(description="Fixture tool.")
    parser.add_argument("--home", default=os.environ.get("FIXTURE_HOME"), help="a|b for <x>")
    sub = parser.add_subparsers(dest="command", required=True)
    job = sub.add_parser("job", help="manage jobs")
    actions = job.add_subparsers(dest="action", required=True)
    add = actions.add_parser("add")
    add.add_argument("name")
    add.add_argument("--kind", choices=("fast", "slow"), default="fast", help="how it runs")
    add.add_argument("--cwd", default=os.getcwd())
    add.add_argument("--retries", type=int, default=0)
    add.add_argument("--tag", action="append", default=[])
    add.add_argument("--quiet", action="store_true")
    parser.parse_args(argv)
'''

EXPECTED = '''# fixture.py

Source: `fixture.py`

Generated by `scripts/cli_reference.py` from this script's own argparse definition, so it never drifts. The other scripts are listed in the [command-line reference](README.md).

A usage line shows a required flag bare and an optional one in brackets. `[flags]` stands for the flags of the command before it, listed in that command's section.

```text
fixture.py [--home HOME] <command>
```

Fixture tool.

| Argument | Required | Choices | Default | Help |
| --- | --- | --- | --- | --- |
| `--home HOME` |  |  |  | a\\|b for \\<x> |

`<command>` is one of `job`.

## fixture.py job

```text
fixture.py [flags] job <action>
```

manage jobs

`<action>` is one of `add`.

## fixture.py job add

```text
fixture.py [flags] job add [--kind KIND] [--cwd CWD] [--retries RETRIES] [--tag TAG] [--quiet] name
```

| Argument | Required | Choices | Default | Help |
| --- | --- | --- | --- | --- |
| `name` | yes |  |  |  |
| `--kind KIND` |  | `fast`, `slow` | `fast` | how it runs |
| `--cwd CWD` |  |  | `$PWD` |  |
| `--retries RETRIES` |  |  | `0` |  |
| `--tag TAG` (repeatable) |  |  |  |  |
| `--quiet` |  |  |  |  |
'''

GROUPS = '''
import argparse

def main(argv=None):
    parser = argparse.ArgumentParser()
    one = parser.add_mutually_exclusive_group(required=True)
    one.add_argument("--left", "-l", metavar="SIDE")
    one.add_argument("--right", action="store_true")
    parser.add_argument("--must", required=True)
    most = parser.add_mutually_exclusive_group()
    most.add_argument("--dry-run", action="store_true")
    most.add_argument("--to-file", action="store_true")
    parser.add_argument("id", nargs="?")
    parser.add_argument("cmd", nargs=argparse.REMAINDER)
    parser.parse_args(argv)
'''

GROUPS_EXPECTED = '''```text
groups.py (--left SIDE | --right) --must MUST [--dry-run | --to-file] [id] ...
```

| Argument | Required | Choices | Default | Help |
| --- | --- | --- | --- | --- |
| `--left, -l SIDE` |  |  |  |  |
| `--right` |  |  |  |  |
| `--must MUST` | yes |  |  |  |
| `--dry-run` |  |  |  |  |
| `--to-file` |  |  |  |  |
| `id` |  |  |  |  |
| `cmd` |  |  |  |  |

Give exactly one of `--left`, `--right`.

Give at most one of `--dry-run`, `--to-file`.
'''

HOSTILE = {"BRIGADE_DIR": "/tmp/SENTINEL", "FIXTURE_HOME": "/tmp/SENTINEL", "COLUMNS": "40"}


def render(source, name="fixture.py"):
    with tempfile.TemporaryDirectory() as directory:
        (Path(directory) / name).write_text(source)
        text = cli_reference.render_tool(Path(directory), name)
        left = sorted(path.name for path in Path(directory).iterdir())
    return text, left


class CliReferenceTest(unittest.TestCase):
    maxDiff = None

    def test_fixture_renders_nested_commands_choices_defaults_and_missing_help(self):
        with mock.patch.dict(os.environ, HOSTILE):
            text, left = render(FIXTURE)
            self.assertEqual(os.environ["FIXTURE_HOME"], "/tmp/SENTINEL")
        self.assertEqual(text, EXPECTED)
        self.assertEqual(left, ["fixture.py"])

    def test_renamed_flag_changes_the_page(self):
        text, _ = render(FIXTURE.replace('"--kind"', '"--sort"'))
        self.assertEqual(text, EXPECTED.replace("--kind KIND", "--sort SORT"))

    def test_groups_optional_and_remainder_positionals(self):
        text, _ = render(GROUPS, "groups.py")
        self.assertEqual(text.split("\n\n", 4)[4], GROUPS_EXPECTED)

    def test_tool_that_never_parses_fails_the_render(self):
        with self.assertRaises(SystemExit) as raised:
            render("def main(argv=None):\n    return 0\n")
        self.assertIn("fixture.py: main([]) returned without parsing arguments", str(raised.exception))

    def test_committed_reference_matches_the_generator(self):
        with tempfile.TemporaryDirectory() as elsewhere, mock.patch.dict(os.environ, HOSTILE):
            previous = os.getcwd()
            os.chdir(elsewhere)
            try:
                pages = cli_reference.render()
            finally:
                os.chdir(previous)
        committed = ROOT / "docs/cli"
        self.assertEqual(sorted(path.name for path in committed.iterdir()), sorted(pages), "run python3 scripts/build.py")
        for name, text in pages.items():
            with self.subTest(name):
                self.assertEqual(text, (committed / name).read_text(), "run python3 scripts/build.py")
                self.assertNotIn(str(ROOT), text)

    def test_a_flag_change_in_one_tool_changes_only_that_tools_file(self):
        def pages(kind_flag):
            with tempfile.TemporaryDirectory() as directory:
                (Path(directory) / "one.py").write_text(FIXTURE.replace('"--kind"', f'"{kind_flag}"'))
                (Path(directory) / "two.py").write_text(GROUPS)
                return cli_reference.render(Path(directory), ("one.py", "two.py"))

        before, after = pages("--kind"), pages("--sort")
        self.assertEqual(sorted(before), ["README.md", "one.md", "two.md"])
        self.assertNotEqual(before["one.md"], after["one.md"])
        self.assertEqual(before["README.md"], after["README.md"])
        self.assertEqual(before["two.md"], after["two.md"])

    def test_index_links_every_page(self):
        readme = (ROOT / "docs/cli/README.md").read_text()
        for tool in cli_reference.TOOLS:
            self.assertIn(f"[{Path(tool).name}]({Path(tool).stem}.md)", readme)

    def test_write_replaces_the_directory_without_leaving_stale_pages(self):
        with tempfile.TemporaryDirectory() as directory:
            out = Path(directory) / "cli"
            out.mkdir()
            (out / "gone.md").write_text("stale")
            cli_reference.write(out)
            self.assertEqual(
                sorted(path.name for path in out.iterdir()),
                sorted(["README.md", "activity.md", "brigade.md", "land.md", "roles.md"]),
            )

    def test_every_t3_script_with_a_parser_is_documented(self):
        parsers = sorted(
            str(path.relative_to(ROOT))
            for path in ROOT.glob("t3/**/*.py")
            if "argparse.ArgumentParser(" in path.read_text()
        )
        self.assertEqual(parsers, sorted(cli_reference.TOOLS))
        pages = [cli_reference.page_name(tool) for tool in cli_reference.TOOLS]
        self.assertEqual(sorted(pages), sorted(set(pages)))
        self.assertNotIn(cli_reference.INDEX, pages)


if __name__ == "__main__":
    unittest.main()
