#!/usr/bin/env python3
"""Write docs/skills.md, the catalog of every generated skill and playbook."""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GROUPS = [
    ("Entry point", lambda name: name in {"poteto-help", "poteto-mode"}),
    ("Multi-model workflows", lambda name: name in {"interrogate", "swarm", "arena", "architect", "reflect"}),
    ("Understand", lambda name: name in {"how", "why", "teach", "recall", "blast-radius", "bro"}),
    ("Plan and run long work", lambda name: name in {"brigade", "landing", "figure-it-out", "show-me-your-work"}),
    ("Verify", lambda name: name in {"tdd", "create-verification-skill", "maintain-verification-skill", "benchmark-checklist"}),
    ("Write and clean", lambda name: name in {"unslop", "technical-writing", "no-comments", "typescript-best-practices"}),
    ("Setup and authoring", lambda name: name in {"setup-pstack", "pstack-runtime", "pstack-author-skill", "automate-me", "make-bot-ui", "correct"}),
    ("Principles", lambda name: name.startswith("principle-")),
]


def description(skill_md):
    match = re.search(r"^description:\s*(.+?)\n(?=\w+:|---)", skill_md.read_text(), re.S | re.M)
    text = " ".join(match.group(1).split()) if match else ""
    return text.strip().strip("\"'").replace("\\\"", "\"").replace("|", "\\|")


def playbooks(skills):
    text = (skills / "poteto-mode/SKILL.md").read_text()
    section = text.split("## Playbooks", 1)[1]
    rows = []
    for name, summary in re.findall(r"^- \*\*(.+?)\.\*\* (.+)$", section, re.M):
        path = re.search(r"`(playbooks/[\w-]+\.md)`", summary)
        summary = re.sub(r"\s*(Full steps: )?`playbooks/[\w-]+\.md`\.?", "", summary).strip()
        link = f"[{name}](../skills/poteto-mode/{path.group(1)})" if path else name
        rows.append(f"| {link} | {summary.replace('|', '/')} |")
    return rows


def render(skills):
    names = sorted(p.parent.name for p in skills.glob("*/SKILL.md"))
    lines = [
        "# Skills",
        "",
        "Every skill pstack-t3 installs. Generated by `scripts/catalog.py` from each skill's own description, so it never drifts.",
        "",
        "Invoke any skill in a T3 composer with `$name`. `$poteto-mode` calls most of the others for you as its playbook steps need them.",
        "",
    ]
    placed = set()
    for title, member in GROUPS:
        group = [name for name in names if member(name) and name not in placed]
        if not group:
            continue
        placed.update(group)
        lines += [f"## {title}", "", "| Skill | What it does |", "| --- | --- |"]
        lines += [f"| [`{name}`](../skills/{name}/SKILL.md) | {description(skills / name / 'SKILL.md')} |" for name in group]
        lines.append("")
    rest = [name for name in names if name not in placed]
    if rest:
        lines += ["## Other", "", "| Skill | What it does |", "| --- | --- |"]
        lines += [f"| [`{name}`](../skills/{name}/SKILL.md) | {description(skills / name / 'SKILL.md')} |" for name in rest]
        lines.append("")
    rows = playbooks(skills)
    lines += ["## poteto-mode playbooks", "", "`$poteto-mode` matches your request to one of these and follows its steps. Opening a PR runs at the end of the others.", "",
              "| Playbook | For |", "| --- | --- |", *rows, ""]
    return "\n".join(lines)


def write(skills=ROOT / "skills", out=ROOT / "docs/skills.md"):
    out.parent.mkdir(exist_ok=True)
    out.write_text(render(skills))
    return out


if __name__ == "__main__":
    print(f"wrote {write(Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'skills')}")
