#!/usr/bin/env python3
"""Write docs/cli/<script>.md for each script pstack-t3 ships, and the docs/cli/README.md index."""

import argparse
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS = (
    "t3/added/brigade/scripts/brigade.py",
    "t3/added/landing/scripts/land.py",
    "t3/scripts/roles.py",
)
CWD = "$PWD"
OUT = ROOT / "docs/cli"
INDEX = "README.md"
HEAD = [
    "Generated by `scripts/cli_reference.py` from this script's own argparse definition, so it never drifts. The other scripts are listed in the [command-line reference](README.md).",
    "",
    "A usage line shows a required flag bare and an optional one in brackets. `[flags]` stands for the flags of the command before it, listed in that command's section.",
    "",
]
POSITIONAL = {None: "{}", "?": "[{}]", "*": "[{} ...]", "+": "{} ...", argparse.REMAINDER: "..."}


class Found(BaseException):
    """Carries the parser out of a tool's main(). BaseException, so no tool's `except Exception` can swallow it."""


def trap(parser, *args, **kwargs):
    raise Found(parser)


def load(path):
    """Return the ArgumentParser that path's main() builds, without parsing anything.

    The source runs in a plain dict, outside the import system, so no
    __pycache__ appears beside it. While main([]) runs, os.environ is empty and
    os.getcwd() returns CWD, so no default can hold a machine value.
    """
    environ, getcwd, parse = dict(os.environ), os.getcwd, argparse.ArgumentParser.parse_known_args
    scope = {"__name__": path.stem, "__file__": str(path)}
    try:
        os.environ.clear()
        os.getcwd = lambda: CWD
        argparse.ArgumentParser.parse_known_args = trap
        exec(compile(path.read_text(), str(path), "exec"), scope)
        scope["main"]([])
    except Found as found:
        return found.args[0]
    finally:
        argparse.ArgumentParser.parse_known_args = parse
        os.getcwd = getcwd
        os.environ.clear()
        os.environ.update(environ)
    raise SystemExit(f"{path}: main([]) returned without parsing arguments")


def subcommands(parser):
    """Return (dest, [(name, child, help)]) in declaration order, or (None, []).

    help is the parent's help= for that name, else the child's description, else None.
    """
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            helps = {choice.dest: choice.help for choice in action._choices_actions}
            return action.dest, [(name, child, helps.get(name) or child.description) for name, child in action.choices.items()]
    return None, []


def arguments(parser):
    return [a for a in parser._actions if not isinstance(a, (argparse._HelpAction, argparse._SubParsersAction))]


def text(value):
    """One line of prose safe in a table cell. GitHub reads a bare | as a column and a bare < as HTML."""
    return " ".join((value or "").split()).replace("|", "\\|").replace("<", "\\<")


def token(action, names=None):
    """How one argument reads: `--flag`, `--flag VALUE`, `id`, `[id]`, or `...`. names defaults to the first option string."""
    value = action.metavar or (action.dest.upper() if action.option_strings else action.dest)
    if not action.option_strings:
        return POSITIONAL[action.nargs].format(value)
    names = names or action.option_strings[0]
    return names if action.nargs == 0 else f"{names} {value}"


def usage(prefix, parser):
    """prefix, then flags, then positionals, then <dest> when the parser has subcommands. Never wraps."""
    grouped = {id(a): g for g in parser._mutually_exclusive_groups for a in g._group_actions}
    flags, seen = [], set()
    for action in arguments(parser):
        if not action.option_strings or id(action) in seen:
            continue
        group = grouped.get(id(action))
        members = group._group_actions if group else [action]
        seen.update(id(member) for member in members)
        body = " | ".join(token(member) for member in members)
        if group.required if group else action.required:
            flags.append(f"({body})" if group else body)
        else:
            flags.append(f"[{body}]")
    positionals = [token(a) for a in arguments(parser) if not a.option_strings]
    dest, children = subcommands(parser)
    return " ".join([prefix, *flags, *positionals, *([f"<{dest}>"] if children else [])])


def table(parser):
    """The argument table lines, plus one sentence per mutually exclusive group. [] when there are no arguments."""
    rows = []
    for action in arguments(parser):
        name = f"`{token(action, ', '.join(action.option_strings))}`" if action.option_strings else f"`{action.dest}`"
        name += " (repeatable)" if isinstance(action, argparse._AppendAction) else ""
        required = action.required if action.option_strings else action.nargs in (None, "+")
        choices = ", ".join(f"`{choice}`" for choice in action.choices or ())
        default = action.default
        # `is False`, because 0 == False and a default of 0 is worth showing.
        default = "" if default is None or default is False or default == "" or default == [] else f"`{default}`"
        rows.append(f"| {name} | {'yes' if required else ''} | {choices} | {default} | {text(action.help)} |")
    lines = ["| Argument | Required | Choices | Default | Help |", "| --- | --- | --- | --- | --- |", *rows, ""] if rows else []
    for group in parser._mutually_exclusive_groups:
        names = ", ".join(f"`{member.option_strings[0]}`" for member in group._group_actions)
        lines += [f"Give {'exactly' if group.required else 'at most'} one of {names}.", ""]
    return lines


def section(level, path, prefix, parser, help_text):
    """One heading, usage block, help text, and table, then the same for every subcommand, depth first.

    Every subcommand gets a `##` heading at any depth.

    path is the command without flags and names the heading. prefix is path with
    `[flags]` after each ancestor that has flags, and opens the usage line.
    """
    lines = [f"{level} {path}", "", "```text", usage(prefix, parser), "```", ""]
    lines += [line for block in (help_text or "").split("\n\n") if text(block) for line in (text(block), "")]
    lines += table(parser)
    dest, children = subcommands(parser)
    if children:
        lines += [f"`<{dest}>` is one of " + ", ".join(f"`{name}`" for name, _, _ in children) + ".", ""]
    inherited = prefix + (" [flags]" if any(a.option_strings for a in arguments(parser)) else "")
    for name, child, child_help in children:
        lines += section("##", f"{path} {name}", f"{inherited} {name}", child, child_help)
    return lines


def page_name(tool):
    return Path(tool).stem + ".md"


def render_tool(root, tool):
    """The page for one script. It reads that script alone, so a change to another script cannot change it."""
    name = Path(tool).name
    parser = load(root / tool)
    lines = section("#", name, name, parser, parser.description)
    return "\n".join([*lines[:2], f"Source: `{tool}`", "", *HEAD, *lines[2:]])


def render_index(tools=TOOLS):
    """The index. It lists names and paths only, so a flag change in one script never changes it."""
    lines = [
        "# Command-line reference",
        "",
        "Every command and flag of the scripts pstack-t3 ships, one page per script. Each page is generated by `scripts/cli_reference.py` from the script's own argparse definition, so it never drifts.",
        "",
        *(f"- [{Path(tool).name}]({page_name(tool)}), source `{tool}`" for tool in tools),
        "",
    ]
    return "\n".join(lines)


def render(root=ROOT, tools=TOOLS):
    """Return {file name: text} for every file under docs/cli."""
    pages = {page_name(tool): render_tool(root, tool) for tool in tools}
    return {INDEX: render_index(tools), **pages}


def write(out=OUT, root=ROOT, tools=TOOLS):
    """Write every page and delete any other .md file in out, so a script dropped from TOOLS leaves no stale page."""
    pages = render(root, tools)
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("*.md"):
        if stale.name not in pages:
            stale.unlink()
    for name, text in pages.items():
        (out / name).write_text(text)
    return out


if __name__ == "__main__":
    print(f"wrote {write()}")
